fix display driver issues in recovery
JF002/InfiniTime pull request #245
Opened 2021-03-20 18:37 UTC by petterhs

Fixing build errors in DisplayAppRecover.cpp and recoveryLoader.cpp after new updates to display driver

2021-03-20 18:48 UTC, joaquimorg requested changes
The new function joins the old ones so the parameters must be the ones that already existed.

2021-03-20 18:48 UTC, joaquimorg commented on src/displayapp/DisplayAppRecovery.cpp
> +    lcd.DrawBuffer(0, 0, displayWidth, displayHeight, reinterpret_cast<const uint8_t *>(displayBuffer), displayWidth * 2);
this is wrong, must be
lcd.DrawBuffer(0, i, displayWidth, 1, reinterpret_cast<const uint8_t *>(displayBuffer), displayWidth * bytesPerPixel);

2021-03-20 18:48 UTC, joaquimorg commented on src/displayapp/DisplayAppRecovery.cpp
> +    lcd.DrawBuffer(0, 0, displayWidth, displayHeight, reinterpret_cast<const uint8_t *>(displayBuffer), displayWidth * 2);
lcd.DrawBuffer(0, displayWidth - barHeight + i, barWidth, 1,reinterpret_cast<const uint8_t *>(displayBuffer), barWidth * bytesPerPixel);

2021-03-20 18:48 UTC, joaquimorg commented on src/recoveryLoader.cpp
> +    lcd.DrawBuffer(0, 0, displayWidth, displayHeight, reinterpret_cast<const uint8_t *>(displayBuffer), displayWidth * 2);
lcd.DrawBuffer(0, i, displayWidth, 1, reinterpret_cast<const uint8_t *>(displayBuffer), displayWidth * bytesPerPixel);

2021-03-20 18:48 UTC, joaquimorg commented on src/recoveryLoader.cpp
> +    lcd.DrawBuffer(0, 0, displayWidth, displayHeight, reinterpret_cast<const uint8_t *>(displayBuffer), displayWidth * 2);
lcd.DrawBuffer(0, displayWidth - barHeight + i, barWidth, 1, reinterpret_cast<const uint8_t *>(displayBuffer), barWidth * bytesPerPixel);

2021-03-21 11:43 UTC, petterhs commented
Oh thank you! I was not thorough enough with this..

2021-03-21 15:35 UTC, merged