Rewrite MemoryAnalysis.md with up to date information.
JF002/InfiniTime pull request #411
Opened 2021-06-03 19:01 UTC by JF002

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +Note that the NRF52832 cannot execute code stored in the external flash : we need to store the whole firmware in the internal flash memory, and use the external one to store graphicals assets, fonts,
```suggestion
Note that the NRF52832 cannot execute code stored in the external flash: we need to store the whole firmware in the internal flash memory, and use the external one to store graphicals assets, fonts...
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +A binary is composed of multiple sections. Most of the time, these sections are .text, .rodata, .data and .bss but more sections can be defined in the linker script.
```suggestion
A binary is composed of multiple sections. Most of the time, these sections are:
.text, .rodata, .data, and .bss
but more sections can be defined in the linker script.
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +The internal flash memory stores the whole firmware : code, variable that are not default-initialized, constants,...
```suggestion
The internal flash memory stores the whole firmware: code, variable that are not default-initialized, constants...
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +Using this tool, you can easily see the size of each symbol relative to the other one, check what is using most of the space,...
```suggestion
Using this tool, you can easily see the size of each symbol relative to the other one, and check what is using most of the space...
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +Also, as Linkermapviz is written in Python, you can easily modify it to adapt it to your firmware, export data in another format,... For example, [I modified it to parse the content of the MAP file a
```suggestion
Also, as Linkermapviz is written in Python, you can easily modify it to adapt it to your firmware, export data in another format... For example, [I modified it to parse the contents of the MAP file and export it in a CSV file](https://github.com/JF002/InfiniTime/issues/313#issuecomment-842338620). I could later on open this file in LibreOffice Calc and use sort/filter functionality to search for specific symbols in specific files...
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +[Puncover](https://github.com/HBehrens/puncover) is another useful tools that analyses the binary file generated by the compiler (the .out file that contains all debug information). It provides valua
```suggestion
[Puncover](https://github.com/HBehrens/puncover) is another useful tools that analyses the binary file generated by the compiler (the .out file that contains all debug information). It provides valuable information about the symbols (data and code): name, position, size, max stack of each functions, callers, callees...
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> + - Run : `puncover --gcc_tools_base=/home/jf/nrf52/gcc-arm-none-eabi-9-2020-q2-update/bin/a-none-eabi- --elf_file /home/jf/git/PineTime/cmake-build-release/src/pinetime-app-1.1.0.out --src_root /home
The path's need to be made more "universal" in my opinion, but I'm not sure how.
Something like this:
*luse `/path/to/folder-or-file` where the path is, abd add a note to change it to the real path.

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +RAM memory contains all the data that can be modified at run-time: variables, stack, heap,...
```suggestion
RAM memory contains all the data that can be modified at run-time: variables, stack, heap...
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +You can easily analyze the memory used by variables declared in the global scope using the MAP. You'll find them int the sections .BSS or .DATA. Linkermapviz and Puncover can be used to analyze their
```suggestion
You can easily analyze the memory used by variables declared in the global scope using the MAP. You'll find them in the .BSS or .DATA sections. Linkermapviz and Puncover can be used to analyze their memory usage.
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +Variables declared in the scope of a function will be allocated on the stack. It means that the stack usage will vary according to the state of the program, and cannot be easily analyze at compile ti
```suggestion
Variables declared in the scope of a function will be allocated on the stack. It means that the stack usage will vary according to the state of the program, and cannot be easily analyzed at compile time.
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +hexdump ram.bin -v  |less
```suggestion
hexdump ram.bin -v  | less
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +The heap is declared in the [linker script](https://github.com/JF002/InfiniTime/blob/develop/nrf_common.ld#L136) and its current size is 8192 bytes. The heap is used for dynamic memory allocation(`ma
```suggestion
The heap is declared in the [linker script](https://github.com/JF002/InfiniTime/blob/develop/nrf_common.ld#L136) and its current size is 8192 bytes. The heap is used for dynamic memory allocation(`malloc()`, `new`...).
```

2021-06-03 19:34 UTC, Itai-Nelken commented on doc/MemoryAnalysis.md
> +FreeRTOS uses this buffer to allocate memory for tasks stack and all the RTOS object created during runtime (timers, mutexes,...).
```suggestion
FreeRTOS uses this buffer to allocate memory for tasks stack and all the RTOS object created during runtime (timers, mutexes...).
```

2021-06-04 01:54 UTC, MysteriousLog6 requested changes
Replace `Flash memories and used in ` with `Flash memories are used in `

2021-06-05 13:29 UTC, JF002 commented
Thanks @Itai-Nelken and @MysteriousLog6 :+1:

2021-06-12 09:02 UTC, merged